require('core.plugins_config.color-scheme')
require('core.plugins_config.lualine')
require('core.plugins_config.nvim-tree')
require('core.plugins_config.telescope')
require('core.plugins_config.treesitter')
