return {
	"nvim-treesitter/nvim-treesitter",
	branch = "master",
	build = ":TSUpdate",
	lazy = false,
	opts = {
		ensure_installed = {
			"c",
			"cpp",
			"lua",
			"vim",
			"vimdoc",
			"query",
			"markdown",
			"markdown_inline",
			"python",
			"javascript",
			"typescript",
			"go",
			"php",
			"html",
			"css",
			"csv",
			"sql",
			"bash",
			"json",
			"yaml",
			"toml",
			"regex",
			"rust",
			"java",
			"dockerfile",
		},
		sync_install = false,
		auto_install = true,
		highlight = {
			enable = true,
		},
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
	end,
}
